### ISSUE TITLE
Extra white space

### ISSUE THREAD

**Issue by JoJo10Smith** [Workday/prism-python#47]
Hi, I'm thinking of contributing to this repo and I'm familiarizing myself with code. I noticed that there were a few whitespaces (found with flake8) in two of the files: `_version.py` and `versioneer.py` An example of the `flake8` output for the current file has been attached. Please view the `E203 whitespace before ':'`

![image](https://github.com/Workday/prism-python/assets/64989097/2730d986-491e-4b69-a8c8-02fd05320ace)

While this is a relatively small issue and the changes would not affect the performance, I would still like to submit a PR for this and will do so. If it is decided that the changes will not be merged I can move on to trying to look at the other issues.

**Comment by CurtLH** [comment]
As per [setup.cfg](https://github.com/Workday/prism-python/blob/master/setup.cfg#L6-L11),  versioneer is exempt from flake8.
